# Generated by Django 4.1.1 on 2022-09-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField(blank=True, null=True)),
                ('num2', models.TextField(blank=True, null=True)),
                ('num3', models.IntegerField(blank=True, null=True)),
                ('num4', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
